import registerComponent from "./core/registerComponent";
import ButtonRadius from './components/ButtonRadius';
import ContainerInputAuth from './blocks/ContainerInputAuth';
import InputAuth from './components/InputAuth';
import ErrorComponent from './components/ErrorComponent';
import Card from "./blocks/Card";
import LinkAuth from "./components/LinkAuth";
import SearchHeader from "./blocks/SearchHeader";
import SearchInput from "./components/LinkAuth";
import Chat from "./blocks/Chat";
import MessageComponent from "./blocks/MessageComponent";
import MessageComponentHeader from "./blocks/MessageComponentHeader";
import MessageRow from "./blocks/MessageRow";
import MessageUser from "./blocks/MessageUser";
import Message from "./components/Message";
import SendButton from "./components/SendButton";
import {Profile} from "./blocks/Profile/Profile";
import ProfileRow from "./blocks/ProfileRow";
import ProfileInput from "./components/ProfileInput";
import ProfileButton from "./components/ButtonProfile";
import {FormElement} from "./blocks/FormElement/FormElement";

registerComponent(ButtonRadius);
registerComponent(ContainerInputAuth);
registerComponent(InputAuth);
registerComponent(ErrorComponent);
registerComponent(Card);
registerComponent(LinkAuth);
registerComponent(SearchHeader);
registerComponent(SearchInput);
registerComponent(Chat);
registerComponent(MessageComponent);
registerComponent(MessageComponentHeader);
registerComponent(MessageRow);
registerComponent(Message);
registerComponent(MessageUser);
registerComponent(SendButton);
registerComponent(Profile);
registerComponent(ProfileRow);
registerComponent(ProfileInput);
registerComponent(ProfileButton);
registerComponent(FormElement);